package com.evol.dao.mapper;

import com.evol.entity.SeckillOrder;
import com.evol.entity.SeckillOrderExample;
import com.evol.entity.SeckillOrderKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    long countByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int deleteByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SeckillOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int insert(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int insertSelective(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    List<SeckillOrder> selectByExample(SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    SeckillOrder selectByPrimaryKey(SeckillOrderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SeckillOrder record, @Param("example") SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SeckillOrder record, @Param("example") SeckillOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SeckillOrder record);
}