package com.evol.entity;

import java.util.Date;

public class SeckillOrder extends SeckillOrderKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_order.pay_amount
     *
     * @mbg.generated
     */
    private Integer payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_order.state
     *
     * @mbg.generated
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_order.pay_amount
     *
     * @return the value of seckill_order.pay_amount
     *
     * @mbg.generated
     */
    public Integer getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_order.pay_amount
     *
     * @param payAmount the value for seckill_order.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(Integer payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_order.state
     *
     * @return the value of seckill_order.state
     *
     * @mbg.generated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_order.state
     *
     * @param state the value for seckill_order.state
     *
     * @mbg.generated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_order.create_time
     *
     * @return the value of seckill_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_order.create_time
     *
     * @param createTime the value for seckill_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}