package com.evol.entity;

import java.util.Date;

public class Seckill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.stock_number
     *
     * @mbg.generated
     */
    private Long stockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.cost_price
     *
     * @mbg.generated
     */
    private Long costPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.id
     *
     * @return the value of seckill.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.id
     *
     * @param id the value for seckill.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.title
     *
     * @return the value of seckill.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.title
     *
     * @param title the value for seckill.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.image
     *
     * @return the value of seckill.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.image
     *
     * @param image the value for seckill.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.stock_number
     *
     * @return the value of seckill.stock_number
     *
     * @mbg.generated
     */
    public Long getStockNumber() {
        return stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.stock_number
     *
     * @param stockNumber the value for seckill.stock_number
     *
     * @mbg.generated
     */
    public void setStockNumber(Long stockNumber) {
        this.stockNumber = stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.price
     *
     * @return the value of seckill.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.price
     *
     * @param price the value for seckill.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.cost_price
     *
     * @return the value of seckill.cost_price
     *
     * @mbg.generated
     */
    public Long getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.cost_price
     *
     * @param costPrice the value for seckill.cost_price
     *
     * @mbg.generated
     */
    public void setCostPrice(Long costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.start_time
     *
     * @return the value of seckill.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.start_time
     *
     * @param startTime the value for seckill.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.end_time
     *
     * @return the value of seckill.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.end_time
     *
     * @param endTime the value for seckill.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.create_time
     *
     * @return the value of seckill.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.create_time
     *
     * @param createTime the value for seckill.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}